filebeat.inputs:
- type: docker
  containers:
    ids: "*"
    path: '/var/lib/docker/containers'
    stream: "all"

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "elastic"
  indices:
    - index: "filebeat"

logging.json: true
logging.metrics.enabled: false