filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
              contains:
                docker.container.image: "elastic"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              exclude_lines: [".*"]



processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["newelasticsearch:9200"]
  username: "elastic"
  password: "elastic"
  indices:
    - index: "filebeat"

logging.json: true
logging.metrics.enabled: false
