version: "3.7"

services:

  grafana:
    image: grafanadev
    container_name: ${PLATFORM_STACK_NAME}-grafana
    restart: unless-stopped
    build:
      context: ./grafana/
      dockerfile: Dockerfile
    env_file:
      .env
    ports:
      - "3000:3000"
    volumes:
      - grafana-dashboards:/var/lib/grafana
      - grafana-data:/etc/grafana/
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${PLATFORM_STACK_NAME}-grafana.rule=Host(`${DOMAIN}`)  && PathPrefix(`/monitoring`)
      - traefik.http.routers.${PLATFORM_STACK_NAME}-grafana.service=${PLATFORM_STACK_NAME}-grafana
      - traefik.http.services.${PLATFORM_STACK_NAME}-grafana.loadbalancer.server.port=3000
      - traefik.http.routers.${PLATFORM_STACK_NAME}-grafana.entrypoints=websecure
      - traefik.http.routers.${PLATFORM_STACK_NAME}-grafana.tls.certresolver=letsencrypt
      - traefik.http.routers.${PLATFORM_STACK_NAME}-grafana.tls=true
      - traefik.http.routers.${PLATFORM_STACK_NAME}-grafana.middlewares=${PLATFORM_STACK_NAME}-grafana-stripprefix
      - traefik.http.middlewares.${PLATFORM_STACK_NAME}-grafana-stripprefix.stripprefix.prefixes=/monitoring
    networks:
      - traefik-public
      - grafana-network
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"


  mysql:
    image: mysqldev
    container_name: ${PLATFORM_STACK_NAME}-mysql
    restart: unless-stopped
    build:
      context: ./mysql/.
      dockerfile: Dockerfile
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - grafana-network
      - traefik-public
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  prometheus:
    image: prometheusdev
    container_name: ${PLATFORM_STACK_NAME}-prometheus
    restart: unless-stopped
    build:
      context: ./prometheus/.
      dockerfile: Dockerfile
    volumes:
      - prometheus-data:/prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - grafana-network
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: ${PLATFORM_STACK_NAME}-monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /datadrive/docker/containers/:/datadrive/docker/containers/:ro
    expose:
      - 8080
    networks:
      - grafana-network
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"


  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: ${PLATFORM_STACK_NAME}-monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - grafana-network
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  filebeat:
    image: filebeatdev
    container_name: ${PLATFORM_STACK_NAME}-filebeat
    build:
      context: ./filebeat/.
      dockerfile: Dockerfile
    user: root
    env_file:
      .env
    volumes:
      - type: bind
        source: /datadrive/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: volume
        source: filebeat-data
        target: /usr/share/filebeat/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/filebeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
    networks:
      - grafana-network
      - traefik-public

  grafanaelasticsearch:
    image: elasticsearch:8.2.2
    container_name: ${PLATFORM_STACK_NAME}-grafana-elasticsearch
    restart: unless-stopped
    env_file:
      .env
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - grafana-network
      - traefik-public
    volumes:
      - grafanaelasticsearchelasticsearch-data:/usr/share/elasticsearch/data
      - grafanaelasticsearchelasticsearch-config:/usr/share/elasticsearch/config
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

volumes:
  grafana-dashboards:
  grafana-data:
  mysql-data:
  prometheus-data:
  filebeat-data:
  grafanaelasticsearchelasticsearch-data:
  grafanaelasticsearchelasticsearch-config:


networks:
  traefik-public:
    external: true
  grafana-network:
    external: true